include: package:flutter_lints/flutter.yaml

formatter:
  page_width: 120

linter:
  rules:
    avoid_void_async: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true

analyzer:
  exclude:
    - '**/*.g.dart'
    # - '**/*.freezed.dart'
    - '**/gen_l10n/app_localizations_*.dart'
  errors:
    missing_return: error
    must_be_immutable: error
    must_call_super: error
    invalid_use_of_protected_member: error
    parameter_assignments: error
    sort_unnamed_constructors_first: ignore
    sort_pub_dependencies: ignore
    # json_serializable and freezed compatibility
    invalid_annotation_target: ignore
    constant_identifier_names: ignore
    depend_on_referenced_packages: ignore
