name: misica
description: Yet another Apple Music Player.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.5+1

environment:
  sdk: ^3.7.0

dependencies:
  app_settings: ^6.1.1
  auto_route: ^9.3.0+1
  auto_size_text: ^3.0.0
  cached_network_image: ^3.2.1
  dio: ^5.4.2+1
  dio_cache_interceptor: ^3.2.7
  dio_cache_interceptor_sembast_storage: ^0.2.0
  duration: ^4.0.3
  expandable_text: ^2.3.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^10.0.0-beta.4
  fpdart: ^1.1.0
  freezed_annotation: ^2.2.0
  hooks_riverpod: ^2.1.1
  intl: ^0.19.0
  json_annotation: ^4.8.1
  jwt_decoder: ^2.0.1
  material_floating_search_bar_2: ^0.5.0
  modal_bottom_sheet: ^3.0.0-pre
  music_kit: ^1.2.1
  path: ^1.8.1
  path_provider: ^2.0.11
  retrofit: ^4.1.0
  riverpod_annotation: ^2.3.5
  salomon_bottom_bar: ^3.3.1
  sembast: ^3.2.0+1

dev_dependencies:
  auto_route_generator: ^9.3.1
  build_runner: ^2.4.14
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.2.1
  json_serializable: ^6.5.4
  retrofit_generator: ^9.1.7
  riverpod_generator: ^2.4.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  # assets:
    # Add assets from the images directory to the application.
    # - assets/images/
