name: misica
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  app_settings: ^4.1.6
  auto_route: ^4.0.1
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.4
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^5.0.2
  freezed_annotation: ^2.0.3
  hooks_riverpod: ^1.0.4
  json_annotation: ^4.5.0
  music_kit:
    git:
      url: git@github.com:misiio/flutter_music_kit.git
      ref: master
      path: music_kit
  salomon_bottom_bar: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.0.3+1
  build_runner: ^2.1.11
  json_serializable: ^6.2.0
  auto_route_generator: ^4.0.0

dependency_overrides:
  music_kit:
    path: ../flutter_music_kit/music_kit
  music_kit_platform_interface:
    path: ../flutter_music_kit/music_kit_platform_interface

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
