name: misica
description: Yet another Apple Music Player.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  app_settings: ^4.1.6
  auto_route: ^4.0.1
  auto_size_text: ^3.0.0
  cached_network_image: ^3.2.1
  dartz: ^0.10.1
  dio: ^4.0.6
  dio_cache_interceptor: ^3.2.7
  dio_cache_interceptor_sembast_store: ^1.0.0
  duration: ^3.0.11
  expandable_text: ^2.3.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.4
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^5.0.2
  freezed_annotation: ^2.0.3
  hooks_riverpod: ^2.0.0-dev.9
  intl: ^0.17.0
  json_annotation: ^4.5.0
  jwt_decoder: ^2.0.1
  material_floating_search_bar: ^0.3.7
  music_kit: ^1.0.0
  path: ^1.8.1
  path_provider: ^2.0.11
  retrofit: ^3.0.1+1
  salomon_bottom_bar: ^3.3.1
  sembast: ^3.2.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.0.3+1
  build_runner: ^2.1.11
  json_serializable: ^6.2.0
  auto_route_generator: ^4.0.0
  retrofit_generator: ^4.0.1

dependency_overrides:
  material_floating_search_bar:
    git:
      url: https://github.com/xavier-lyu/material_floating_search_bar.git
      ref: 0.3.7

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
