name: misica
description: Yet another Apple Music Player.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.5+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  app_settings: ^5.1.1
  auto_route: ^8.0.3
  auto_size_text: ^3.0.0
  cached_network_image: ^3.2.1
  dio: ^5.4.2+1
  dio_cache_interceptor: ^3.2.7
  dio_cache_interceptor_sembast_storage: ^0.2.0
  duration: ^3.0.11
  expandable_text: ^2.3.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_secure_storage: ^9.0.0
  fpdart: ^1.1.0
  freezed_annotation: ^2.2.0
  hooks_riverpod: ^2.1.1
  intl: ^0.18.1
  json_annotation: ^4.8.1
  jwt_decoder: ^2.0.1
  material_floating_search_bar_2: ^0.5.0
  modal_bottom_sheet: ^3.0.0-pre
  music_kit: ^1.0.0
  path: ^1.8.1
  path_provider: ^2.0.11
  retrofit: ^4.1.0
  riverpod_annotation: ^2.3.5
  salomon_bottom_bar: ^3.3.1
  sembast: ^3.2.0+1

dev_dependencies:
  auto_route_generator: ^8.0.0
  build_runner: ^2.3.2
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter
  freezed: ^2.2.1
  json_serializable: ^6.5.4
  retrofit_generator: ^8.1.0
  riverpod_generator: ^2.4.0

dependency_overrides:
  # material_floating_search_bar:
  #   git:
  #     url: https://github.com/xavier-lyu/material_floating_search_bar.git
  #     ref: 0.3.7
  music_kit:
    path: ../flutter_music_kit/music_kit

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
